🚧 Update to SDK 30.2.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🚂👨🏽‍🚒🏃🏼‍♂️🕞

Full error log:
Error:  net::ERR_NAME_NOT_RESOLVED at https://collboard.com/

Error:
    at navigate (C:\Users\me\work\collboard\greenhack-mattoni\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:195:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FrameManager.navigateFrame (C:\Users\me\work\collboard\greenhack-mattoni\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:171:21)
    at async Frame.goto (C:\Users\me\work\collboard\greenhack-mattoni\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:584:16)
    at async Page.goto (C:\Users\me\work\collboard\greenhack-mattoni\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1109:16)